ramble/ramble/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('rambleapp.urls')),
    path('admin/', admin.site.urls),
]

ramble/rambleapp/urls.py
from django.urls import path
import social_django
from . import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('index', views.index, name='index'),
  # path('accounts/profile/', views.index, name='index'),
  path('u/<int:user_id>', views.get_user_profile, name='user_profile'),
  path('u/<int:user_id>/likes', views.get_user_profile_likes, name='user_profile_likes'),
  path('u/<int:user_id>/follows', views.get_user_profile_follows, name='user_profile_follows'),
  path('u/<int:user_id>/followers', views.get_user_profile_followers, name='user_profile_followers'),
  path('u/<int:user_id>/collections', views.get_user_profile_collections, name='user_profile_collections'),

  path('collection/<int:collection_id>', views.get_collection, name='collection'),
  path('mycollections/<int:post_id>', views.get_user_collections, name='mycollections'), 
  path('private_collections', views.post_private_collection, name='private_collections'), 

  path('your_stories', views.your_stories, name='your_stories'),
  path('your_stories/published', views.your_stories_published, name='your_stories_published'),
  path('your_stories/drafts', views.your_stories_drafts, name='your_stories_drafts'),

  path('editor_page', views.editor_page, name='editor_page'),

  path('post/<int:post_id>', views.get_ramblepost, name='post'),
  url(r'^draft/<int:draft_id>?preview=true$', views.get_rambledraft),
  path('draft/<int:draft_id>', views.get_rambledraft, name='draft'),

  path('ramblepost', views.post_ramble, name='post_a_ramble'),
  path('save_draft', views.save_draft, name='save_draft'),
  path('load_draft', views.load_draft, name='load_draft'),
  path('deletepost', views.delete_post, name='delete_a_ramble'),
  path('get_post/<int:post_id>', views.get_post, name='get_post'),
  path('get_draft/<int:draft_id>', views.get_draft, name='get_draft'),
  path('likepost', views.like_post, name='like_a_ramble'),
  path('convertpost', views.convert_post, name='convert_a_ramble'),
  path('hidepost', views.hide_post, name='hide_a_ramble'),
  path('amplifypost', views.amplify_post, name='amplify_a_ramble'),  

  path('followuser', views.follow_user, name='follow_a_user'),
  path('block_user', views.block_user, name='block_user'),
  path('mute_user', views.mute_user, name='mute_user'),
  
  path('commentpost', views.post_comment, name='post_a_comment'),
  path('deletecomment', views.delete_comment, name='delete_a_comment'),
  path('addtocollection', views.add_to_collection, name='add_to_collection'),
  path('remove_from_collection', views.remove_from_collection, name='remove_from_collection'),
  path('createcollection', views.create_collection, name='create_collection'),

  path('likes_get/<int:post_id>', views.likes_get, name='likes_get'),

  path('tag/<str:tag_page>', views.get_tagpage, name='tag_page'),

  path('make_profile', views.make_profile, name='edit_your_profile'),
#  path('post_profile', views.post_profile, name='post_profile'),

  path('login', views.login, name='login'),
  path('logout', views.logout, name='logout'),
  path('', views.landing_page, name='landing_page'),
  path('contact', views.contact_us, name="contact_us"),
  path('signin', views.signin, name="signin"),
  path('signup', views.signup, name="signup"),
  path('post_signup', views.post_signup, name="post_signup"),
  path('subscribe_email', views.post_email, name='subscribe_email'),
  path('messages/', include('postman.urls', namespace='postman')),
  path('search', views.search, name='search_results'),
  url(r'^activity/', include('actstream.urls')),
  path('auth/', include('magiclink.urls', namespace='magiclink')),
  # path('accounts/login/', views.login, name='sociallogin'),
  url(r'^oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ramble/rambleapp/forms.py
from django import forms

from PIL import Image
from django.core.files import File

from .models import Profile, InterestedUsers, Photo


class ProfileForm(forms.ModelForm):
    # profilepic = forms.ImageField()
    # fullname = forms.CharField()
    # bio = forms.CharField()
    class Meta:
        model = Profile
        exclude = ['user_id']

class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

ramble/rambleapp/views.py
import os
import json 
import datetime
from django.shortcuts import redirect

# Create your views here.
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate
from django.contrib.auth.models import User as Auth_User
from django.contrib.auth.forms import UserChangeForm
from django.db import IntegrityError
from django.shortcuts import render

from social_django.models import UserSocialAuth

from .models import Post, Like, Follow, Profile, InterestedUsers, Comment, Collection, CollectionPost, Blocked, Muted, HidePost
from .forms import ProfileForm

from actstream import action
import re #SRM Notifications
from backports.pbkdf2 import pbkdf2_hmac
#from .AESCipher import *
from simple_aes_cipher import AESCipher, generate_secret_key

from json.encoder import JSONEncoder #json encode for sending json to edit post
    
from magiclink.helpers import create_magiclink

# Page

def landing_page(request):
    template = loader.get_template('rambleapp/landing_page.html')
    context = {}
    return HttpResponse(template.render(context, request))

def contact_us(request):
    template = loader.get_template('rambleapp/contact_us.html')
    context = {}
    return HttpResponse(template.render(context, request))

def signin(request):
    if request.method=='GET':
        template = loader.get_template('rambleapp/signin.html')
        context = {}
        return HttpResponse(template.render(context, request))

def signup(request):
    if request.method=='GET':
        template = loader.get_template('rambleapp/signup.html')
        context = {}
        return HttpResponse(template.render(context, request))
    
def post_signup(request):
    if request.method=='POST': 
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["psw"]
        confirmation = request.POST["psw-repeat"]
        if password != confirmation:
            return render(request, "rambleapp/signup.html", {
                "message": "Passwords must match."
            })
        # Salted password SRM
        #password = bytes(password, 'utf-8')
        if not type(password) == bytes:
            password = password.encode()
        size = 10
        salt = os.urandom(size)
        pass_key = pbkdf2_hmac("sha256", password, salt, 50000, 32)
        pass_key = str(pass_key)
        #print(type(pass_key))
        #pass_key = unicode(pass_key, errors='ignore')
        #pass_key = pass_key.encode("utf8","ignore")
        #pass_key = to_bytes(pass_key.encode('utf-8'))
        #try:
        #    pass_key = pass_key.decode()
        #    print("Here")
        #except (UnicodeDecodeError, AttributeError):
        #    print("Error")
        #    pass

        key = 'Store login securely'
        key = generate_secret_key(key)
        cipher = AESCipher(key)
        encrypt_text = cipher.encrypt(pass_key)
        print(encrypt_text)
        assert pass_key != encrypt_text

        #pass_key = cipher.encrypt(plain_text=pass_key)
        # Salted password SRM

        try:
            user = Auth_User.objects.create_user(username, email, encrypt_text) #Salted password SRM 
            user.save()
        except IntegrityError as e:
            print(e)
            return render(request, "rambleapp/signup.html", {
                "message": "Email address already taken."
            })
        user = authenticate(request, username=username, password=encrypt_text) #Salted password SRM
        if user is not None:
            auth_login(request, user, backend="django.contrib.auth.backends.ModelBackend")
        #user = Auth_User.objects.get(username=username).pk
        #form = ProfileForm(request.POST, request.FILES)
        #template = loader.get_template('rambleapp/make_profile.html')
        #context = {}
        #return HttpResponse(template.render(context, request))
        return redirect(make_profile)
    return HttpResponseForbidden('allowed only via POST')
    
def post_email(request):
    if request.POST:
        email = request.POST['email']
        try:
            emailobj = InterestedUsers.objects.get(email_id=email)
        except InterestedUsers.DoesNotExist:
            new_interested_user = InterestedUsers(email_id=email)
            new_interested_user.save()
        return HttpResponse(204)
    return HttpResponseForbidden("Allowed Only Via Post")

def search(request):
    query = request.POST.get('search_ramble')
    object_list = Post.objects.filter(post_title__icontains=query) 
    user_list =  Auth_User.objects.filter(username__icontains = query)
    template = loader.get_template('rambleapp/search_results.html')
    context = {'object_list': object_list, 'user_list' : user_list, 'query': query  }
    return HttpResponse(template.render(context, request))

@login_required
def index(request):
    user = Auth_User.objects.get(pk=request.user.id) 
    try:
        user_profile = Profile.objects.get(user_id=request.user.id)
    except Profile.DoesNotExist:
        return redirect(make_profile)

    template = loader.get_template('rambleapp/index.html')

    # get all previous posts
    #posts = Post.objects.all().order_by('-post_timestamp')
    posts = Post.objects.filter(status=1).order_by('-post_timestamp')
    drafts = Post.objects.filter(status=0).order_by('-post_timestamp')

    posts_and_likes = [(post, len(Like.objects.filter(post_id=post) )) for post in posts]
    amplify_posts = {(Post.objects.filter(pk=post.id,status=1).values('id', 'amplify_count')) for post in posts}
    drafts_and_likes = [(draft, len(Like.objects.filter(post_id=draft))) for draft in drafts]
    user_hide_posts = list(set([hide_post.post_id.id for hide_post in HidePost.objects.filter(hide_status=0)]))
    user_liked_posts = set([like.post_id.id for like in Like.objects.filter(user_id=user)])
    user_followers = set([follow.followee_id.id for follow in Follow.objects.filter(follower_id=user)])
    collection_posts = [post.post_id.pk for post in CollectionPost.objects.filter(collection_id__user_id=user)]
    #SRM Show Collections on TL
    all_collections = Collection.objects.filter(collection_status= 0)
    all_collection_posts = [] #UnBoundLocalError otherwise
    for collection in all_collections:
        all_collection_posts = [post for post in CollectionPost.objects.all()]
    #SRM Private collections on TL
    all_private_collection_posts = []
    private_collections = Collection.objects.filter(collection_status= 1)
    private_collections = list(set(private_collections))
    for pri_col in private_collections:
        all_private_collection_posts = [post for post in CollectionPost.objects.filter(collection_id = pri_col)]
    #SRM Private collections on TL
    
    context = {'posts': posts, 'user_liked_posts': user_liked_posts,
               'user_followers': user_followers, 'user_profile': user_profile,
               'posts_and_likes': posts_and_likes, 'user_collected_posts': collection_posts,
               'drafts': drafts, 'drafts_and_likes': drafts_and_likes, 
               'amplify_posts': amplify_posts, "all_collections": all_collections ,
               'all_collection_posts': all_collection_posts, 
               'private_collections' : private_collections,
               'all_private_collection_posts' : all_private_collection_posts, 'user_hide_posts': user_hide_posts }
    #SRM Show Collections on TL
    return HttpResponse(template.render(context, request))


@login_required
def make_profile(request):
   # try:
   #    profile = Profile.objects.get(user_id=request.user.id)  
   #     if request.method== "POST":
   #         form = ProfileForm(request.POST, request.FILES)
   #         print("ABCS 1")
   #         if form.is_valid():
   #             form.save()
   #             print("ABCS 2")
   #             return redirect(index)
   #     else:
   #         print("ABCS 3")
   #         form = EditProfileForm(request.POST, request.FILES)
   #         context = { 'form' : form }
   #         return render(request, "rambleapp/make_profile.html", context)
   # except Profile.DoesNotExist:
   #     print("ABCS 4")
   #    form = ProfileForm(request.POST, request.FILES)
   #    template = loader.get_template('rambleapp/make_profile.html')
   #     context = {'form': form}
   #     return HttpResponse(template.render(context, request))

    try:
        profile = Profile.objects.get(user_id=request.user.id)
    except Profile.DoesNotExist:
        profile = Profile()
        
    if request.method == 'POST':
        user = Auth_User.objects.get(pk=request.user.id)
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():  
            new_profile = form.save(commit=False)
            new_profile.user_id = user
            pic = request.FILES.get('id_profile_pic', False)
            if pic != False:
                new_profile.profile_pic = pic
            else: 
                new_profile.profile_pic = "profilepix/default_dog.jpg"
            new_profile.save()
            return redirect(index)
        else:
            return redirect(make_profile)            
    else:
        form = ProfileForm(instance=profile)
        context = { 'form' : form }
        return render(request, "rambleapp/make_profile.html", context) 

# user profile helper methods: 

def twitter_user_context(request_obj):
    context = {}
    try:
        twitter_login = request_obj.user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None
    except AttributeError:
        twitter_login = None
    if twitter_login:
        user = Auth_User.objects.get(pk=request_obj.user.id)
        user_profile = Profile.objects.get(user_id=request_obj.user.id)

ramble/rambleapp/templates/magiclink/login_email.html
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Simple Transactional Email</title>
    <style>
    /* -------------------------------------
        INLINED WITH htmlemail.io/inline
    ------------------------------------- */
    /* -------------------------------------
        RESPONSIVE AND MOBILE FRIENDLY STYLES
    ------------------------------------- */
    @media only screen and (max-width: 620px) {
      table[class=body] h1 {
        font-size: 28px !important;
        margin-bottom: 10px !important;
      }
      table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
        font-size: 16px !important;
      }
      table[class=body] .wrapper,
            table[class=body] .article {
        padding: 10px !important;
      }
      table[class=body] .content {
        padding: 0 !important;
      }
      table[class=body] .container {
        padding: 0 !important;
        width: 100% !important;
      }
      table[class=body] .main {
        border-left-width: 0 !important;
        border-radius: 0 !important;
        border-right-width: 0 !important;
      }
      table[class=body] .btn table {
        width: 100% !important;
      }
      table[class=body] .btn a {
        width: 100% !important;
      }
      table[class=body] .img-responsive {
        height: auto !important;
        max-width: 100% !important;
        width: auto !important;
      }
    }

    /* -------------------------------------
        PRESERVE THESE STYLES IN THE HEAD
    ------------------------------------- */
    @media all {
      .ExternalClass {
        width: 100%;
      }
      .ExternalClass,
            .ExternalClass p,
            .ExternalClass span,
            .ExternalClass font,
            .ExternalClass td,
            .ExternalClass div {
        line-height: 100%;
      }
      .apple-link a {
        color: inherit !important;
        font-family: inherit !important;
        font-size: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
        text-decoration: none !important;
      }
      #MessageViewBody a {
        color: inherit;
        text-decoration: none;
        font-size: inherit;
        font-family: inherit;
        font-weight: inherit;
        line-height: inherit;
      }
    }
    </style>
  </head>
  <body class="" style="background-color: {{ style.background_color }}; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;">
    <table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: {{ style.background_color }};">
      <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
        <td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;">
          <div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;">

            <!-- START CENTERED WHITE CONTAINER -->
            <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0; text-align: center;">{{ subject }}</span>
            <table class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: {{ style.background_color }}; border-radius: 3px;">

              {% if style.logo_url %}
              <img src="{{ style.logo_url }}" alt="logo" width="90" height="90" border="0" style="border:0; outline:none; text-decoration:none; display:block; Margin: 0 auto 15px auto;">
              {% endif %}
              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;">
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                    <tr>
                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">
                        <p style="font-family: sans-serif; font-size: 18px; font-weight: normal; margin: 0; Margin-bottom: 20px; line-height: 23px; text-align: center; color: {{ style.main_text_color }};">
                          Click to confirm and sign in. This link will expire in {{ expiry|timeuntil }}
                        </p>
                        <table border="0" cellpadding="0" cellspacing="0" class="btn btn-primary" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box; margin: 30px 0;">
                          <tbody>
                            <tr>
                              <td align="left" style="font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;">
                                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto; margin: 0 auto;">
                                  <tbody>
                                    <tr>
                                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top; background-color: {{ style.button_background_color }}; border-radius: 5px;">
                                          <a href="{{ magiclink }}" target="_blank" style="display: inline-block; color: {{ style.button_text_color }}; background-color: {{ style.button_background_color }}; border-radius: 5px; box-sizing: border-box; cursor: pointer; text-decoration: none; font-size: 14px; font-weight: bold; margin: 0; padding: 12px 25px;">Click here to sign in</a>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 35px; text-align: center; color: {{ style.main_text_color }};">
                          Or sign in using this link:
                          <br />
                          <a href="{{ magiclink }}" style="color: {{ style.main_text_color }}; word-break: break-word; font-size: 0.9em;">{{ magiclink }}</a>
                        </p>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 20px; text-align: center; color: {{ style.main_text_color }};">
                          Please do not forward this message to anyone else, if you do they will be able to access your account
                        </p>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 20px; text-align: center; color: {{ style.main_text_color }};">
                          If you did not request this link, you can safely ignore this email.
                        </p>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>

          <!-- END CENTERED WHITE CONTAINER -->
          </div>
        </td>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
      </tr>
    </table>
  </body>
</html>

ramble/rambleapp/templates/magiclink/login_failed.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <!-- SRM -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/fleuron_transparent_icon.ico' %}"/>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <title>Ramble - Write, Read, Curate - Login</title>

</head>

<body style="margin:10px 10px 10px 10px;">
  <div class="header">
    <nav class="navbar navbar-light navbar-1 white">
        <div class="container-fluid">
            <a class="navbar-brand" href="#""></a>
        </div>
    </nav>
  
    <a href="#"><img class="headerimg" src="{% static 'images/fleuron_header_reverse_transparent.png' %}" width=300px"
         style="margin-right:5px;margin-top:5px;background-color:#fcfcfc"/></a>
  </div>
  <h1>Login failed</h1>
  <p>It was not possible to log you in due to:</p>
  <p>{{ login_error }}</p>

  <p>There are several possible ways for logins to fail with the current Django MagicLink settings:</p>
  <ul>
    <li>The URL you are trying to use is malformed</li>
    <li>The magic link you tried to use has expired</li>
    <li>You have already used this magic link to login before</li>
    {% if ONE_TOKEN_PER_USER %}
    <li>You have requested another magic causing this magic link to become invalid</li>
    {% endif %}
    {% if REQUIRE_SAME_BROWSER %}
    <li>You are using a different browser to when you requested the login link</li>
    {% endif %}
    {% if REQUIRE_SAME_IP %}
    <li>You are trying to login from a different location or machine that you requested the login link from</li>
    {% endif %}
    {% if not ALLOW_SUPERUSER_LOGIN or not ALLOW_STAFF_LOGIN %}
    <li>You are a superuser or staff user</li>
    {% endif %}
  </ul>

</body>
</html>

ramble/rambleapp/templates/magiclink/login_ml.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <!-- SRM -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/fleuron_transparent_icon.ico' %}"/>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <title>Ramble - Write, Read, Curate - Login</title>

  <style type="text/css">
    /* Hide the antispan field labels for the  Django's defailt form output */
    label[for="id_url"], label[for="id_load_time"] {
      display: none;
    }
  </style>


</head>

<body style="margin:10px 10px 10px 10px;">
  <div class="header">
    <nav class="navbar navbar-light navbar-1 white">
        <div class="container-fluid">
            <a class="navbar-brand" href="#""></a>
        </div>
    </nav>
  
  <a href="#"><img class="headerimg" src="{% static 'images/fleuron_header_reverse_transparent.png' %}" width=300px"
         style="margin-right:5px;margin-top:5px;background-color:#fcfcfc"/></a>
        </div>
  <h1 style="text-align: center;">Login via email</h1>
  <form style="text-align: center;" action="{% url 'magiclink:login' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}" method="post">
    {% csrf_token %}
    {{ login_form }}
    <button type="submit">Send login email</button>
  </form>
  {% if require_signup %}
    <p>Don't have an account? <a href="{% url 'magiclink:signup' %}">Sign up here</a></p>
  {% endif %}

</body>
</html>

ramble/rambleapp/templates/magiclink/login_sent.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <!-- SRM -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/fleuron_transparent_icon.ico' %}"/>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <title>Ramble - Write, Read, Curate - Login</title>

</head>

<body style="margin:10px 10px 10px 10px;">
  <div class="header">
    <nav class="navbar navbar-light navbar-1 white">
        <div class="container-fluid">
            <a class="navbar-brand" href="#""></a>
        </div>
    </nav>
  
    <a href="#"><img class="headerimg" src="{% static 'images/fleuron_header_reverse_transparent.png' %}" width=300px"
         style="margin-right:5px;margin-top:5px;background-color:#fcfcfc"/></a>
  </div>

  <h1 style="text-align: center;">Please check your email</h1>
  <p style="text-align: center;">
      We have sent you a magic link to your email address<br />
      Click the link to login automatically
  </p>
</body>
</html>

ramble/rambleapp/templates/magiclink/signup.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Django MagicLink Sign up - Please override this template</title>
  <meta name="description" content="Django MagicLink">
  <meta name="author" content="Django MagicLink">
  <style type="text/css">
    /* Hide the antispan field labels for the  Django's defailt form output */
    label[for="id_url"], label[for="id_load_time"] {
      display: none;
    }
  </style>
</head>

<body>
  <h1>Create an account</h1>
  <form action="{% url 'magiclink:signup' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}" method="post">
    {% csrf_token %}
    {{ SignupForm }}
    <button type="submit">Sign up</button>
  </form>
  <p>Already have an account? <a href="{% url 'magiclink:login' %}">Log in here</a></p>

  <p>If you are seeing this you have not yet overridden the 'MAGICLINK_SIGNUP_TEMPLATE_NAME' setting yet.</p>
  <p>Please see the <a href="https://github.com/pyepye/django-magiclink">README on Github</a> for more details on setting up django-magiclink correctly</p>
</body>
</html>